export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'apple-blue':      '#0066cc',
        'apple-blue-focus':'#0071e3',
        'apple-blue-dark': '#2997ff',
        'apple-ink':       '#1d1d1f',
        'apple-ink-80':    '#333333',
        'apple-ink-48':    '#7a7a7a',
        'apple-parchment': '#f5f5f7',
        'apple-pearl':     '#fafafc',
        'apple-hairline':  '#e0e0e0',
        'apple-divider':   '#f0f0f0',
        'apple-chip':      '#d2d2d7',
        'apple-tile-1':    '#272729',
        'apple-tile-2':    '#2a2a2c',
        'apple-tile-3':    '#252527',
      },
      borderRadius: {
        'apple-sm': '8px',
        'apple-md': '11px',
        'apple-lg': '18px',
      },
      fontSize: {
        'apple-hero':    ['56px', { lineHeight: '1.07', letterSpacing: '-0.28px',  fontWeight: '600' }],
        'apple-display': ['40px', { lineHeight: '1.10', letterSpacing: '0',        fontWeight: '600' }],
        'apple-tagline': ['21px', { lineHeight: '1.19', letterSpacing: '0.231px', fontWeight: '600' }],
        'apple-body':    ['17px', { lineHeight: '1.47', letterSpacing: '-0.374px', fontWeight: '400' }],
        'apple-caption': ['14px', { lineHeight: '1.43', letterSpacing: '-0.224px', fontWeight: '400' }],
        'apple-nav':     ['12px', { lineHeight: '1.0',  letterSpacing: '-0.12px',  fontWeight: '400' }],
        'apple-fine':    ['12px', { lineHeight: '1.0',  letterSpacing: '-0.12px',  fontWeight: '400' }],
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'system-ui', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      typography: ({ theme }) => ({
        apple: {
          css: {
            '--tw-prose-body':        theme('colors.apple-ink'),
            '--tw-prose-headings':    theme('colors.apple-ink'),
            '--tw-prose-lead':        theme('colors.apple-ink-48'),
            '--tw-prose-links':       theme('colors.apple-blue'),
            '--tw-prose-bold':        theme('colors.apple-ink'),
            '--tw-prose-counters':    theme('colors.apple-ink-48'),
            '--tw-prose-bullets':     theme('colors.apple-ink-48'),
            '--tw-prose-hr':          theme('colors.apple-hairline'),
            '--tw-prose-quotes':      theme('colors.apple-ink'),
            '--tw-prose-quote-borders': theme('colors.apple-hairline'),
            '--tw-prose-captions':    theme('colors.apple-ink-48'),
            '--tw-prose-code':        theme('colors.apple-ink'),
            '--tw-prose-pre-code':    '#f5f5f7',
            '--tw-prose-pre-bg':      '#1d1d1f',
            '--tw-prose-th-borders':  theme('colors.apple-hairline'),
            '--tw-prose-td-borders':  theme('colors.apple-hairline'),
            '--tw-prose-invert-body':     '#f5f5f7',
            '--tw-prose-invert-headings': '#f5f5f7',
            '--tw-prose-invert-links':    '#2997ff',
            '--tw-prose-invert-bold':     '#f5f5f7',
            '--tw-prose-invert-counters': '#98989d',
            '--tw-prose-invert-bullets':  '#98989d',
            '--tw-prose-invert-hr':       '#3a3a3c',
            '--tw-prose-invert-quotes':   '#f5f5f7',
            '--tw-prose-invert-quote-borders': '#3a3a3c',
            '--tw-prose-invert-captions': '#98989d',
            '--tw-prose-invert-code':     '#f5f5f7',
            '--tw-prose-invert-pre-code': '#f5f5f7',
            '--tw-prose-invert-pre-bg':   '#2c2c2e',
            '--tw-prose-invert-th-borders': '#3a3a3c',
            '--tw-prose-invert-td-borders': '#3a3a3c',
            fontSize: '17px',
            lineHeight: '1.47',
            fontFamily: '-apple-system, BlinkMacSystemFont, system-ui, "Helvetica Neue", Arial, sans-serif',
            'h1, h2, h3, h4': {
              fontFamily: '-apple-system, BlinkMacSystemFont, system-ui, "Helvetica Neue", Arial, sans-serif',
              letterSpacing: '0',
            },
            h2: { fontSize: '21px', lineHeight: '1.19', fontWeight: '600' },
            h3: { fontSize: '19px', lineHeight: '1.21', fontWeight: '600' },
            a: { textDecoration: 'none', '&:hover': { opacity: '0.7' } },
            'code::before': { content: '""' },
            'code::after':  { content: '""' },
            code: {
              backgroundColor: '#f0f0f0',
              borderRadius: '6px',
              padding: '2px 6px',
              fontSize: '14px',
            },
            img: { borderRadius: '11px' },
            blockquote: {
              fontStyle: 'normal',
              borderLeftColor: theme('colors.apple-blue'),
            },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
